version: "3.7"

services:
  api:
    container_name: mlibre-api
    build: ./api
    env_file: ./api/.env
    ports:
      - 5000:5000

  web:
    container_name: mlibre-client
    build: ./client
    env_file: ./client/.env
    ports:
      - 3000:3000
    depends_on:
      - api
