version: "3.7"

services:
  api:
    container_name: mlibre-api
    image: node
    ports: ["5000:5000"]
    env_file: ./api/.env
    volumes:
      - ./api:/opt/api
    command: sh -c "cd opt/api && npm install && npm start"

  web:
    container_name: mlibre-client
    image: node
    ports: ["3000:3000"]
    env_file: ./client/.env
    volumes:
      - ./client:/opt/client
    command: sh -c "cd opt/client && npm install && npm start"
    depends_on:
      - api
